language: c
compiler: clang
install:
 - git clone https://github.com/ninja-build/ninja.git /tmp/ninja
 - pushd /tmp/ninja
 - git checkout release
 - python configure.py --bootstrap
 - export PATH=/tmp/ninja:$PATH
 - popd
 - pip install --user ninja-syntax
 - git clone https://github.com/Maratyszcza/PeachPy.git /tmp/PeachPy
 - pushd /tmp/PeachPy
 - pip install --user --upgrade -r requirements.txt
 - python setup.py generate
 - pip install --user --upgrade .
 - popd
before_script:
 - python ./configure.py --backend=psimd
 - ninja
script:
 - ninja smoketest
addons:
  apt:
    packages:
    - linux-headers-3.13.0-40-generic
    - python-pip
